### ISSUE TITLE
UseCapDashboard is now internal

### ISSUE THREAD

**Issue by jirisykora83** [dotnetcore/CAP#1244]
`UseCapDashboard` is mark as internal with `7.0.0` is that intended. If so, how it should be replaced?

**Comment by yang-xiaodong** [comment]
The dashboard middleware will register automatically in ASP.NET Core, Users don't need to register it.

**Comment by jirisykora83** [comment]
Then after upgrading to v7 and removing `UseCapDashboard` from startup I wont access dashboard anymore (I literally change just cap nugget package version and remove this one line).

**Comment by yang-xiaodong** [comment]
```
services.AddCap(x =>
{
    // Add this line
    x.UseDashboard();
}
```

**Comment by jirisykora83** [comment]
yes this is something what I already have even with 6.2.1 because we use custom path and basic authentication because azureAD do not work for as and basic auth is fine for our usecase).

**Comment by yang-xiaodong** [comment]
https://github.com/dotnetcore/CAP/issues/792

In your case, is the basic auth middleware registration sequence before UseCapDashboard?

**Comment by jirisykora83** [comment]
I don't in 6.2.1. With 7.0.0 a cannot call `UseCapDashboard` as it is internal. If you mean `UseDashboard` inside `AddCap` I try it move AddAuthentication before AddCap but is seems like it still not work for me.

I also try remove authentication and my custom path but i am still not able to reach `/cap`.

On same app I hosting blazor app which somehow could collide with way the cap handle its dashboard?

Maybe it could be nice have some default logging in `CapStartupFilter` just to make sure it is actually called?

**Comment by yang-xiaodong** [comment]
Can you provide a reproducible example repository for us ?

**Comment by ggjnone** [comment]
Same issue here, I have a blazor server app and with previous version it worked well, finding the cap route for the Dashboard. With 7.0.0 it stopped working. Same configurations its just the UseCapDashboard is being called explicitly.

**Comment by yang-xiaodong** [comment]
Fixed in [7.0.1](https://github.com/dotnetcore/CAP/releases/tag/v7.0.1)

**Comment by jirisykora83** [comment]
It still not works i create default blazor wasm app (with checked option for hosted in asp.net)

Put this in top section (literally only change what i made - not sure if it worth creating github repo for that).

```
builder.Services.AddCap(x =>
{
	x.UseInMemoryStorage();
	x.UseInMemoryMessageQueue();

	x.UseDashboard(opts =>
	{
		opts.PathMatch = "/cap-dashboard";
	});
});
```

packages in "server" project

```
  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP" Version="7.0.1" />
    <PackageReference Include="DotNetCore.CAP.InMemoryStorage" Version="7.0.1" />
	<PackageReference Include="DotNetCore.CAP.MongoDB" Version="7.0.1" />
	<PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="7.0.1" />
	<PackageReference Include="DotNetCore.CAP.Dashboard" Version="7.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="7.0.1" />
    <PackageReference Include="Savorboard.CAP.InMemoryMessageQueue" Version="7.0.0" />
  </ItemGroup>
```

And dashboard route serves just blazor app.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/7279825/209799158-c2228929-2072-4ee7-97e3-83e2cbb531f4.png">

just in case it's not use custom path but it same.
<img width="428" alt="image" src="https://user-images.githubusercontent.com/7279825/209799182-14c0acbb-c5e8-42ea-abb8-b9a47d4780bd.png">

**Comment by yang-xiaodong** [comment]
I found out that due to my browser client side 301 redirect caching, the issue wasn't really fixed in 7.0.1, it will be fixed in 7.0.2.

Blazor wasm is not supported!

**Comment by jirisykora83** [comment]
Did you means cap cannot be use with wasm hosting from v7.0+? Because it was working with v6.

**Comment by yang-xiaodong** [comment]
Yes,  Blazor wasm It runs in the browser, it does not have the ASP.NET Core environment required by CAP dashboard.

Blazor wasm sdk is `Microsoft.NET.Sdk.BlazorWebAssembly` not contains  `Microsoft.AspNetCore.App` framework
```cs
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
```

Blazor server sdk is  `Microsoft.NET.Sdk.Web`
```cs
<Project Sdk="Microsoft.NET.Sdk.Web">
```

If CAP Dashboard is referenced in the Blazor WASM project, this compilation error will occur
```
There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm
```

**Comment by jirisykora83** [comment]
Ok i understand it cannot runs in browser i am not sure if there is any problem in same asp instance serve/host blazor app and cap.

I tried 7.0.2 (last nuget as now) and dashboard endpoint is not reachable but it shows just white page as it is not loading any assets.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/7279825/211391182-828da4c0-9fca-4421-bd27-fe902d618505.png">

**Comment by yang-xiaodong** [comment]
Are you map the fallback route ?  see https://github.com/dotnetcore/CAP/issues/1256

**Comment by jirisykora83** [comment]
I use `endpoints.MapFallbackToAreaPage("{*path:nonfile}", "/_FrontendHost", "Frontend");` as it should be same as your example but it not works for me.

Now a was able to solve this as in my case i use asp to host multiple blazor app. And as last entry in startup.cs I have

```
app.Map(
	"",
	builder =>
	{
		builder.UseRouting();
		builder.UseEndpoints(endpoints =>
		{
			// Fallback for blazor front-end
			endpoints.MapFallbackToAreaPage("{*path:nonfile}", "/_FrontendHost", "Frontend");
		});
	});
```

which for whatever reason causes this. So, if anybody have same issue (mostly likely not) i just change it to this:

```
app.MapWhen(
	x => !x.Request.Path.StartsWithSegments(CapConst.CapDashboardPath)
	builder =>
	{
		builder.UseRouting();
		builder.UseEndpoints(endpoints =>
		{
			// Fallback for blazor front-end
			endpoints.MapFallbackToAreaPage("{*path:nonfile}", "/_FrontendHost", "Frontend");
		});
	});
```

Thanks for your help :)
