### ISSUE TITLE
MySql Connect Timeout expired.  All pooled connections are in use

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnetcore/CAP#931]
This is because `DotNetCore.CAP.MySql`  reference the `MySqlConnector` version 1.3.1, and it's a bug that exists in this version, we will fix it in version 5.1.1.

You can manually reference the latest MySqlConnector in the project to solve this problem as well.

**Comment by yang-xiaodong** [comment]
Fixed in 5.1.1

**Comment by WangJunZzz** [comment]
i use cap6.0.0  but  still exist.
![image](https://user-images.githubusercontent.com/25657426/153799743-362d2d54-dc40-4f8a-8572-2bc97113f52f.png)
