### ISSUE TITLE
Consumer register cancellation token source null reference 

### ISSUE THREAD

**Issue by EashShow** [dotnetcore/CAP#952]
测试过程中，并没有使用到CAP相关功能。
机器配置如下：
CPU：i5-6400 4Core
内存：8G
网络：回环

测试工具：JMeter
线程数：3000

测试过程中：CPU100%，内存100%

错误信息如下：
2021-07-19 18:21:25,064 WARN  DotNetCore.CAP.Internal.ConsumerRegister - RabbitMQ consumer cancelled. --> amq.ctag-snpfkK3zg284Ij9GVZbO6Q
2021-07-19 18:21:25,065 WARN  DotNetCore.CAP.Internal.ConsumerRegister - RabbitMQ consumer shutdown. --> Unexpected Exception
2021-07-19 18:21:28,306 WARN  DotNetCore.CAP.Processor.TransportCheckProcessor - Transport connection is unhealthy, reconnection...
2021-07-19 18:21:28,308 WARN  DotNetCore.CAP.Processor.InfiniteRetryProcessor - Processor 'DotNetCore.CAP.Processor.TransportCheckProcessor' failed. Retrying...
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetCore.CAP.Internal.ConsumerRegister.ReStart(Boolean force)
   at DotNetCore.CAP.Processor.TransportCheckProcessor.ProcessAsync(ProcessingContext context)
   at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context)
2021-07-19 18:21:31,306 WARN  DotNetCore.CAP.Processor.TransportCheckProcessor - Transport connection is unhealthy, reconnection...
2021-07-19 18:21:31,307 WARN  DotNetCore.CAP.Processor.InfiniteRetryProcessor - Processor 'DotNetCore.CAP.Processor.TransportCheckProcessor' failed. Retrying...
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetCore.CAP.Internal.ConsumerRegister.ReStart(Boolean force)
   at DotNetCore.CAP.Processor.TransportCheckProcessor.ProcessAsync(ProcessingContext context)
   at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context)
2021-07-19 18:21:34,306 WARN  DotNetCore.CAP.Processor.TransportCheckProcessor - Transport connection is unhealthy, reconnection...
2021-07-19 18:21:34,306 WARN  DotNetCore.CAP.Processor.InfiniteRetryProcessor - Processor 'DotNetCore.CAP.Processor.TransportCheckProcessor' failed. Retrying...
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetCore.CAP.Internal.ConsumerRegister.ReStart(Boolean force)
   at DotNetCore.CAP.Processor.TransportCheckProcessor.ProcessAsync(ProcessingContext context)
   at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context)

**Comment by yang-xiaodong** [comment]
Fixed in v5.1.2

**Comment by Linc-li** [comment]
I think this issue is still occurred in my local environment. Currently don't know the reason.
